Giving Your Way/Models/CatalogViewModel.cs
using System.Collections.Generic;

namespace Giving_Your_Way.Models
{
	public class CatalogViewModel
	{
		public int CatalogId { get; set; }
		public string CatalogName{ get; set; }
		public string CatalogDescription { get; set; }
		
	}
}

Giving Your Way/Models/OrganizationCatalogsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Giving_Your_Way.Models
{
	public class OrganizationCatalogsViewModel
	{
		public List<CatalogViewModel> Catalogs { get; set; }
		public UserViewModel CatalogOwnerDetails { get; set; }
	}
}

Giving Your Way/Models/ProductViewModelcs.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Giving_Your_Way.Models
{
	public class ProductViewModelcs
	{
		//private long Id { get; set; }
		//private long name { get; set; }
		//private long descr { get; set; }
	}
}

Giving Your Way/Models/UserViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Giving_Your_Way.Models
{
	public class UserViewModel
	{
		public int Id { get; set; }
		public string Name { get; set; }
		public string ImageUrl { get; set; }
		public string About { get; set; }
		public string Address { get; set; }

	}
}

Giving Your Way/Controllers/CatalogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Model;
using Domain.Services;
using Giving_Your_Way.Models;

namespace Giving_Your_Way.Controllers
{
	public class CatalogController : Controller
	{
		private readonly IPlatformApi _IPlatformApi;

		public CatalogController(IPlatformApi IPlatformApi)
		{
			_IPlatformApi = IPlatformApi;
		}
		//
		// GET: /Catalog/

		public ActionResult Index(string token, int? catalogId)
		{
			var organizationId = "5740405";
			var catalogsIds = new List<int> { 9951104, 9951126 };
			var catalogs = _IPlatformApi.GetCatalogs(catalogsIds, token);
			List<UserModel> organization = _IPlatformApi.GetUserProfileData(organizationId, token);
			var catalogsViewModel = InitCatalogs(catalogs, organization.FirstOrDefault());
			return View(catalogsViewModel);
		}

		private OrganizationCatalogsViewModel InitCatalogs(List<CatalogModel> catalogs, UserModel organization)
		{
			var organizationCatalogs = new OrganizationCatalogsViewModel();
			organizationCatalogs.Catalogs = new List<CatalogViewModel>();
			foreach (var catalogModel in catalogs)
			{
				var catalog = new CatalogViewModel();
				catalog.CatalogDescription = catalogModel.Description;
				catalog.CatalogName = catalogModel.Name;
				catalog.CatalogId = catalogModel.Id;
				
				organizationCatalogs.Catalogs.Add(catalog);
			}
			organizationCatalogs.CatalogOwnerDetails = new UserViewModel();
			organizationCatalogs.CatalogOwnerDetails.Address = organization.AboutMe;
			//catalog.CatalogOwnerDetails.About = "catalog Owner About";
			organizationCatalogs.CatalogOwnerDetails.ImageUrl =
				"http://sandboxstatic1.shopyourway.com/getImage?url=http%3a%2f%2fc.shld.net%2frpx%2fi%2fs%2fpi%2fmp%2f19845%2f3743179508%3fsrc%3dhttp%253A%252F%252Fecx.images-amazon.com%252Fimages%252FI%252F31Ih3o3Q1ML.jpg%26d%3d1d2ffe6cd15e4335b54abb30c87678625d6e3395&t=Catalog&w=100&h=100&qlt=75&mrg=1&s=4db9c1043e4aee6af7409c308564e75d";
			organizationCatalogs.CatalogOwnerDetails.Name = organization.FullName.FirstName + " " + organization.FullName.LastName;
			organizationCatalogs.CatalogOwnerDetails.Id = organization.UserId;
			return organizationCatalogs;

		}

	}
}

Giving Your Way/Controllers/LandingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using Domain.Model;
using Domain.Services;
using Giving_Your_Way.Models;

namespace Giving_Your_Way.Controllers
{
    public class LandingController : Controller
    {
		private readonly IPlatformApi _IPlatformApi;

		public LandingController(IPlatformApi IPlatformApi)
		{
			_IPlatformApi = IPlatformApi;
		}
        //
        // GET: /Landing/

        public RedirectToRouteResult Index()
        {
			return RedirectToRoute("catalogs/index", new { token = Request.Params["token"] }); //Action( "Index"); //, new { mobile = true }

	        //return "ok";
        }
		public ActionResult Organizations(string token)
		{
			var organizationsId = "5740405,5740389,5740388,5740412,5740387,5740410,5740413";
			List<UserModel> organizations = _IPlatformApi.GetUserProfileData(organizationsId, Request.Params["token"]);
			var organizationsViewModel = InitOrganizations(organizations);
			return View(organizationsViewModel);
		}

		private List<UserViewModel> InitOrganizations(List<UserModel> organizations)
		{
			var organizationsList = new List<UserViewModel>();
			foreach (var organization in organizations)
			{
				var organizationModel = new UserViewModel();
				organizationModel.Address = organization.AboutMe;
				//catalog.CatalogOwnerDetails.About = "catalog Owner About";
				organizationModel.ImageUrl =
					"http://sandboxstatic1.shopyourway.com/getImage?url=http%3a%2f%2fc.shld.net%2frpx%2fi%2fs%2fpi%2fmp%2f19845%2f3743179508%3fsrc%3dhttp%253A%252F%252Fecx.images-amazon.com%252Fimages%252FI%252F31Ih3o3Q1ML.jpg%26d%3d1d2ffe6cd15e4335b54abb30c87678625d6e3395&t=Catalog&w=100&h=100&qlt=75&mrg=1&s=4db9c1043e4aee6af7409c308564e75d";
				organizationModel.Name = organization.FullName.FirstName + " " +
				                                                organization.FullName.LastName;
				organizationModel.Id = organization.UserId;
				organizationsList.Add(organizationModel);
			}
			return organizationsList;
		}

    }
}

Giving Your Way/Controllers/OrganizationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Giving_Your_Way.App_Start
{
    public class OrganizationController : Controller
    {
        //
        // GET: /Organization/

        public ActionResult Index()
        {
            return View();
        }

    }
}

Giving Your Way/Views/Catalog/Index.cshtml
@using System.Web.DynamicData
@using Microsoft.Ajax.Utilities
@model  Giving_Your_Way.Models.OrganizationCatalogsViewModel
@{
	<div class="wrapper" style="width: 90%; margin: auto; padding-top: 50px;">

		<div class="organization-details" style="height: 160px;">
			@{
				var imageSrc = "../Images/5740405Icon.jpg";
				if (Model.CatalogOwnerDetails.Id == 5740405)
				{
					imageSrc = "../Images/5740405Icon.jpg";
				}
			}
			<img src="@imageSrc" style=" height: 140px;width: 170px; float: left;"/>
			<div class="details" style="float: left; padding-top: 16px;">
				<div class="name" ><span class="title" style="">Organization:</span> <span class="detail">@Model.CatalogOwnerDetails.Name</span>  </div>
				<div class="address"><span class="title">Address:</span> <span class="detail">@Model.CatalogOwnerDetails.Address</span> </div>
				@{ var url = Url.Action("organizations", "Landing", new {token = Request.Params["token"]});}
				<div class="change"><a style="display: block" href="@url">Change Organization</a></div>

			</div>
		</div>

		<div class="catalogs" style="width: 100%; margin: auto;">


			@foreach (var catalog in Model.Catalogs)
   {
				<div class="catalog">
					<div class="title" >
						@catalog.CatalogName
					</div>

					@{ var src = "http://sandbox.shopyourway.com/widgets/catalog/products?catalogId=" + catalog.CatalogId + "&background=#FFFFFF"; }
					<iframe marginheight="0" marginwidth="0" frameborder="0" scrolling="no" width="100%" height="416px" src="@src"></iframe>
				</div>
   }
		</div>
	</div>

}

<style>
	.organization-details .name, .organization-details .address, .organization-details .change {
		display: block;
		padding-top: 5px;
		/*float: left;*/
	}

	.organization-details .details .title {
		color: gray;
		font-size: 18px;
		font-weight: 600;
		margin-right: 8px;
		/*float: left;*/
	}

	.organization-details .details .detail {
		font-size: 18px;
		font-weight: 400;
		margin-right: 8px;
		/*float: left;*/
		color: gray;
	}

	.organization-details .change a {
		color: gray;
	}

	.catalogs {
		padding-top: 18px;
	}

	.catalog .title {
		font-size: 18px;
		font-weight: 600;
		color: gray;
		font-family: Helvetica;
		text-align: left;
		line-height: 24px;
		 font-size: 21px;
		  margin-bottom: 30px;

	}

</style>

Giving Your Way/Views/Landing/Organizations.cshtml
@model  List<Giving_Your_Way.Models.UserViewModel>

@{ var url = Url.Action("Index", "Catalog", new { token = Request.Params["token"] });}


<div class="wrapper">
	<div class="descrption">
		Choose your prefered Organization 
	</div>

	<div class="organizations-list">
		@foreach (var org in Model)
  {
			<div class="organization">

				@{
	  var imageSrc = "../Images/5740405Icon.jpg";
	  if (org.Id == 5740405)
	  {
		  imageSrc = "../Images/5740405Icon.jpg";
	  }
	  else if (org.Id == 5740389)
	  {
		  imageSrc = "../Images/5740389Icon.jpg";
	  }
	  else if (org.Id == 5740388)
	  {
		  imageSrc = "../Images/5740388Icon.png";
	  }
	  else if (org.Id == 5740412)
	  {
		  imageSrc = "../Images/5740412Icon.jpg";
	  }
	  else if (org.Id == 5740387)
	  {
		  imageSrc = "../Images/5740387Icon.jpg";
	  }
	  else if (org.Id == 5740410)
	  {
		  imageSrc = "../Images/5740410Icon.jpg";
	  }
	  else if (org.Id == 5740413)
	  {
		  imageSrc = "../Images/5740413Icon.jpg";
	  }
				
				}

				<img src="@imageSrc"/>
			<div class="name">@org.Name</div>
				<a   href="@url" >
				<div class="select" style="background-image: url('../Images/select_bttn.png'); background-repeat: no-repeat;">
					</div>
						</a>

			</div>
  }



	</div>
</div>

<style>
	.wrapper {
		width: 40%;
		margin: auto;
		margin-top: 75px;
	}

	.descrption {
		color: gray;
		font-size: 24px;
		font-weight: 400;
		font-family: Helvetica;
	}

	.organizations-list {
		width: 100%;
		margin: auto;
		padding-top: 50px;
	}

		.organizations-list .organization {
			display: block;
			height: 100px;
			margin-bottom: 15px;
			display: block;
			height: 100px;
			margin-bottom: 15px;
			border: #E8E5FE;
			border-bottom-style: solid;
			border-width: 1px;
		}

			.organizations-list .organization img {
				height: 90px;
				width: 90px;
				float: left;
			}

			.organizations-list .organization .name {
				color: gray;
				font-size: 18px;
				font-weight: 600;
				margin-right: 8px;
				float: left;
				padding-top: 25px;
				margin-left: 26px;
			}

			.organizations-list .organization .select {
				float: right;
				margin-top: 22px;
				height: 43px;
				width: 115px;
				background-size: contain;
			}

				.organizations-list .organization .select a {
					height: 43px;
					width: 115px;
				}
</style>

Giving Your Way/Views/Organization/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

Giving Your Way/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
		<script type="text/javascript" src="http://sandbox.shopyourway.com/platform/loader"></script>

</head>
<body>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>